/**
 * Qiskit Python text exporter for `Circuit` (QSK-01, QSK-02, QSK-03).
 *
 * Produces a runnable Python snippet a reader can paste into a shell
 * with `pip install qiskit`. Used by both the sandbox toolbar and
 * every essay's `CircuitView`, so there is exactly one canonical
 * mapping table — `QISKIT_GATE_MAP` / `QISKIT_ROT_MAP` — and any
 * future simulator gate addition must extend it or the drift test
 * in `tests/quantum/qiskit.test.ts` fails CI.
 *
 * Output shape (locked in PHASE-CONTEXT.md):
 *
 *   # Generated by quantum-site v3 — circuit fragment <fragment>
 *   from qiskit import QuantumCircuit
 *
 *   qc = QuantumCircuit(<n>, <n>)
 *   qc.h(0)
 *   qc.cx(0, 1)
 *   qc.rx(0.7853981633974483, 2)
 *   qc.measure(0, 0)
 *
 * The header fragment is the URL codec output for the same circuit —
 * pasting it back into `/sandbox#<fragment>` reconstructs the editor
 * state. Completes the "remix here ↔ run for real" round-trip.
 */

import {
  type Circuit,
  type DiscreteGate,
  type Op,
  type RotAxis,
  validateCircuit,
} from "./circuit";
import { CodecError, encodeCircuit } from "./codec";

/**
 * Thrown when `toQiskit` cannot emit a snippet (almost always a
 * validation failure on the input circuit). Subclasses `CodecError`
 * so callers can `catch (e) { if (e instanceof CodecError) ... }`
 * uniformly across encode / decode / export paths.
 */
export class QiskitExportError extends CodecError {
  constructor(message: string) {
    super(message);
    this.name = "QiskitExportError";
  }
}

/**
 * Discrete gate → Qiskit `QuantumCircuit` method name (lowercase).
 * Keys are exhaustive over `DiscreteGate` (enforced by `Record<...>`
 * here AND by the QSK-03 drift test that iterates `DISCRETE_GATES`).
 */
export const QISKIT_GATE_MAP: Readonly<Record<DiscreteGate, string>> = {
  X: "x",
  Y: "y",
  Z: "z",
  H: "h",
  S: "s",
  T: "t",
  I: "id",
};

/** Rotation axis → Qiskit method name. */
export const QISKIT_ROT_MAP: Readonly<Record<RotAxis, string>> = {
  X: "rx",
  Y: "ry",
  Z: "rz",
};

export interface ToQiskitOptions {
  /** Optional extra `# ...` line appended to the header comment block. */
  headerComment?: string;
}

/**
 * Return a runnable Qiskit Python snippet for `circuit`.
 *
 * Throws `QiskitExportError` if `validateCircuit` rejects the input
 * or the URL codec can't encode the fragment header. Callers should
 * catch and surface a toast (see `copyQiskitSnippet` in sandbox).
 */
export const toQiskit = (
  circuit: Circuit,
  opts: ToQiskitOptions = {},
): string => {
  try {
    validateCircuit(circuit);
  } catch (err) {
    throw new QiskitExportError((err as Error).message);
  }

  let fragment: string;
  try {
    fragment = encodeCircuit(circuit);
  } catch (err) {
    throw new QiskitExportError((err as Error).message);
  }

  const lines: string[] = [];
  lines.push(
    `# Generated by quantum-site v3 — circuit fragment ${fragment}`,
  );
  if (opts.headerComment) {
    lines.push(`# ${opts.headerComment}`);
  }
  lines.push("from qiskit import QuantumCircuit");
  lines.push("");
  lines.push(`qc = QuantumCircuit(${circuit.qubits}, ${circuit.qubits})`);

  for (const step of circuit.steps) {
    for (const op of step) {
      lines.push(emitOp(op));
    }
  }

  return lines.join("\n") + "\n";
};

/**
 * Emit one Qiskit instruction for a single `Op`. The `default` case
 * uses TS's `never` exhaustiveness check — adding a new variant to
 * the `Op` union without extending this switch fails `npm run build`,
 * which is the *type-level* half of the QSK-03 drift gate. The test
 * file enumerates the runtime mapping tables for the other half.
 */
function emitOp(op: Op): string {
  switch (op.kind) {
    case "gate": {
      const method = QISKIT_GATE_MAP[op.gate];
      if (!method) {
        throw new QiskitExportError(
          `No Qiskit mapping for gate '${op.gate}'`,
        );
      }
      return `qc.${method}(${op.qubit})`;
    }
    case "cnot":
      return `qc.cx(${op.control}, ${op.target})`;
    case "rot": {
      const method = QISKIT_ROT_MAP[op.axis];
      if (!method) {
        throw new QiskitExportError(
          `No Qiskit mapping for rot axis '${op.axis}'`,
        );
      }
      // Full f64 precision; no numpy.pi aliasing — see PHASE-CONTEXT.md.
      return `qc.${method}(${op.theta.toPrecision(17)}, ${op.qubit})`;
    }
    case "measure":
      return `qc.measure(${op.qubit}, ${op.qubit})`;
    default: {
      const _exhaustive: never = op;
      throw new QiskitExportError(
        `Unknown op kind: ${JSON.stringify(_exhaustive)}`,
      );
    }
  }
}
