/**
 * Qiskit exporter tests (QSK-03 drift gate + behavioral coverage).
 *
 * Three suites:
 *   1. Mapping table — one assertion per row of the gate-mapping
 *      table locked in `.planning/phases/01-foundation/PHASE-CONTEXT.md`.
 *   2. Drift coverage — enumerates `DISCRETE_GATES` and `ROT_AXES`
 *      from `circuit.ts` and asserts every value has a Qiskit
 *      mapping. Adding a new simulator gate without a Qiskit entry
 *      fails this test. The TS exhaustiveness check inside `emitOp`
 *      covers the `Op["kind"]` half at compile time.
 *   3. Snapshots — three canonical circuits (Bell, 3-qubit GHZ,
 *      Deutsch oracle Rx(π)) frozen via `toMatchInlineSnapshot` so
 *      future formatting changes surface as PR diff.
 */

import { describe, expect, it, test } from "vitest";
import {
  cnotOp,
  DISCRETE_GATES,
  gateOp,
  measureOp,
  rotOp,
  ROT_AXES,
  type Circuit,
  type Op,
} from "../../src/lib/quantum/circuit";
import { CodecError } from "../../src/lib/quantum/codec";
import {
  QISKIT_GATE_MAP,
  QISKIT_ROT_MAP,
  QiskitExportError,
  toQiskit,
} from "../../src/lib/quantum/qiskit";

/** Build a 1-step circuit that exercises a single op. */
const single = (qubits: number, op: Op): Circuit => ({
  qubits,
  steps: [[op]],
});

describe("toQiskit — gate mapping table", () => {
  // One row per entry of the PHASE-CONTEXT.md gate table.
  test.each([
    ["X gate", single(1, gateOp("X", 0)), "qc.x(0)"],
    ["Y gate", single(2, gateOp("Y", 1)), "qc.y(1)"],
    ["Z gate", single(1, gateOp("Z", 0)), "qc.z(0)"],
    ["H gate", single(1, gateOp("H", 0)), "qc.h(0)"],
    ["S gate", single(1, gateOp("S", 0)), "qc.s(0)"],
    ["T gate", single(1, gateOp("T", 0)), "qc.t(0)"],
    ["I gate", single(1, gateOp("I", 0)), "qc.id(0)"],
    ["CNOT", single(2, cnotOp(0, 1)), "qc.cx(0, 1)"],
    ["measure", single(1, measureOp(0)), "qc.measure(0, 0)"],
  ])("%s emits %s", (_label, circuit, expected) => {
    expect(toQiskit(circuit)).toContain(expected);
  });

  test.each([
    ["Rx", "X" as const, "qc.rx("],
    ["Ry", "Y" as const, "qc.ry("],
    ["Rz", "Z" as const, "qc.rz("],
  ])("rotation %s emits %s", (_label, axis, expected) => {
    const out = toQiskit(single(1, rotOp(axis, 0, Math.PI / 4)));
    expect(out).toContain(expected);
    expect(out).toMatch(/\d+\.\d+e?[+-]?\d*, 0\)/); // theta is a float literal
  });

  it("rotation theta uses full f64 precision (17 sig figs)", () => {
    const theta = Math.PI / 4;
    const out = toQiskit(single(1, rotOp("X", 0, theta)));
    expect(out).toContain(theta.toPrecision(17));
  });

  it("emits one QuantumCircuit(n, n) line with matching widths", () => {
    const out = toQiskit({ qubits: 3, steps: [] });
    expect(out).toContain("qc = QuantumCircuit(3, 3)");
  });

  it("header line includes the URL-codec fragment", () => {
    const out = toQiskit({ qubits: 1, steps: [[gateOp("H", 0)]] });
    expect(out).toMatch(
      /^# Generated by quantum-site v3 — circuit fragment [A-Za-z0-9_-]+\n/,
    );
  });

  it("appends opts.headerComment as a second # line", () => {
    const out = toQiskit(
      { qubits: 1, steps: [[gateOp("H", 0)]] },
      { headerComment: "Hello from /cnot-bell" },
    );
    expect(out).toContain("# Hello from /cnot-bell\n");
  });

  it("imports QuantumCircuit (and nothing else)", () => {
    const out = toQiskit({ qubits: 1, steps: [] });
    expect(out).toContain("from qiskit import QuantumCircuit");
    expect(out).not.toContain("import numpy");
  });
});

describe("toQiskit — drift coverage (QSK-03)", () => {
  it.each(DISCRETE_GATES)(
    "discrete gate %s has a Qiskit mapping",
    (g) => {
      const method = QISKIT_GATE_MAP[g];
      expect(
        method,
        `gate "${g}" has no Qiskit mapping — extend QISKIT_GATE_MAP in src/lib/quantum/qiskit.ts`,
      ).toBeTruthy();
      expect(toQiskit(single(1, gateOp(g, 0)))).toContain(
        `qc.${method}(0)`,
      );
    },
  );

  it.each(ROT_AXES)("rotation axis %s has a Qiskit mapping", (axis) => {
    const method = QISKIT_ROT_MAP[axis];
    expect(
      method,
      `axis "${axis}" has no Qiskit mapping — extend QISKIT_ROT_MAP in src/lib/quantum/qiskit.ts`,
    ).toBeTruthy();
    expect(toQiskit(single(1, rotOp(axis, 0, 1.0)))).toContain(`qc.${method}(`);
  });

  it("QISKIT_GATE_MAP covers exactly DISCRETE_GATES (no extra, no missing)", () => {
    // Sort to make diffs readable; equality enforces both directions.
    expect(Object.keys(QISKIT_GATE_MAP).sort()).toEqual(
      [...DISCRETE_GATES].sort(),
    );
  });

  it("QISKIT_ROT_MAP covers exactly ROT_AXES (no extra, no missing)", () => {
    expect(Object.keys(QISKIT_ROT_MAP).sort()).toEqual([...ROT_AXES].sort());
  });

  // Op.kind coverage is enforced at the type level by emitOp's `never`
  // exhaustiveness check — adding a new variant fails `tsc` / Astro
  // build. The runtime probe here proves every current kind reaches
  // the emitter without throwing.
  it("emits non-empty Qiskit text for every Op.kind", () => {
    const samples: Array<{ kind: Op["kind"]; circuit: Circuit }> = [
      { kind: "gate", circuit: single(1, gateOp("H", 0)) },
      { kind: "cnot", circuit: single(2, cnotOp(0, 1)) },
      { kind: "rot", circuit: single(1, rotOp("Y", 0, Math.PI / 2)) },
      { kind: "measure", circuit: single(1, measureOp(0)) },
    ];
    for (const { kind, circuit } of samples) {
      const out = toQiskit(circuit);
      expect(out, `kind ${kind}`).toMatch(/qc\.\w+\(/);
    }
  });
});

describe("toQiskit — error discipline", () => {
  it("throws QiskitExportError on invalid qubit count", () => {
    expect(() => toQiskit({ qubits: 0, steps: [] })).toThrow(
      QiskitExportError,
    );
  });

  it("QiskitExportError IS a CodecError (uniform catch)", () => {
    try {
      toQiskit({ qubits: 99, steps: [] });
      throw new Error("expected toQiskit to throw");
    } catch (err) {
      expect(err).toBeInstanceOf(CodecError);
      expect(err).toBeInstanceOf(QiskitExportError);
    }
  });

  it("throws QiskitExportError on two ops touching the same qubit in one step", () => {
    expect(() =>
      toQiskit({
        qubits: 1,
        steps: [[gateOp("H", 0), gateOp("X", 0)]],
      }),
    ).toThrow(QiskitExportError);
  });
});

describe("toQiskit — canonical snapshots", () => {
  it("Bell pair (H on 0, CNOT 0→1)", () => {
    const bell: Circuit = {
      qubits: 2,
      steps: [[gateOp("H", 0)], [cnotOp(0, 1)]],
    };
    // Body only (strip the fragment line so the snapshot survives
    // codec wire-format additions); the fragment-line shape is
    // already tested in the mapping suite.
    const body = toQiskit(bell).split("\n").slice(1).join("\n");
    expect(body).toMatchInlineSnapshot(`
      "from qiskit import QuantumCircuit

      qc = QuantumCircuit(2, 2)
      qc.h(0)
      qc.cx(0, 1)
      "
    `);
  });

  it("3-qubit GHZ (H on 0, CNOT 0→1, CNOT 1→2)", () => {
    const ghz: Circuit = {
      qubits: 3,
      steps: [[gateOp("H", 0)], [cnotOp(0, 1)], [cnotOp(1, 2)]],
    };
    const body = toQiskit(ghz).split("\n").slice(1).join("\n");
    expect(body).toMatchInlineSnapshot(`
      "from qiskit import QuantumCircuit

      qc = QuantumCircuit(3, 3)
      qc.h(0)
      qc.cx(0, 1)
      qc.cx(1, 2)
      "
    `);
  });

  it("Deutsch oracle Rx(π) on a single qubit", () => {
    const deutsch: Circuit = {
      qubits: 1,
      steps: [[rotOp("X", 0, Math.PI)]],
    };
    const body = toQiskit(deutsch).split("\n").slice(1).join("\n");
    expect(body).toMatchInlineSnapshot(`
      "from qiskit import QuantumCircuit

      qc = QuantumCircuit(1, 1)
      qc.rx(3.1415926535897931, 0)
      "
    `);
  });
});
